// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpKepzqPj_WF-hYfepZgejRdh_0WS9KgE',
    appId: '1:529083647345:web:a1816116b012adbd4de2d0',
    messagingSenderId: '529083647345',
    projectId: 'flutter-firebase-7b001',
    authDomain: 'flutter-firebase-7b001.firebaseapp.com',
    storageBucket: 'flutter-firebase-7b001.firebasestorage.app',
    measurementId: 'G-D6E3GPF8GT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXcqHA7OkH38gO02mnmjQH0ikMAWeMQqY',
    appId: '1:529083647345:android:fcaf9b6aad06f4da4de2d0',
    messagingSenderId: '529083647345',
    projectId: 'flutter-firebase-7b001',
    storageBucket: 'flutter-firebase-7b001.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRozG6pwB-V36QEZ7yEFZv9UwYtCcQZXQ',
    appId: '1:529083647345:ios:fb0cee7d1c8763684de2d0',
    messagingSenderId: '529083647345',
    projectId: 'flutter-firebase-7b001',
    storageBucket: 'flutter-firebase-7b001.firebasestorage.app',
    iosBundleId: 'com.example.flutterTodoFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRozG6pwB-V36QEZ7yEFZv9UwYtCcQZXQ',
    appId: '1:529083647345:ios:fb0cee7d1c8763684de2d0',
    messagingSenderId: '529083647345',
    projectId: 'flutter-firebase-7b001',
    storageBucket: 'flutter-firebase-7b001.firebasestorage.app',
    iosBundleId: 'com.example.flutterTodoFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpKepzqPj_WF-hYfepZgejRdh_0WS9KgE',
    appId: '1:529083647345:web:4d0c204a211000c54de2d0',
    messagingSenderId: '529083647345',
    projectId: 'flutter-firebase-7b001',
    authDomain: 'flutter-firebase-7b001.firebaseapp.com',
    storageBucket: 'flutter-firebase-7b001.firebasestorage.app',
    measurementId: 'G-PG6K2XKL0M',
  );
}
